import { DocsBody, DocsDescription, DocsPage, DocsTitle } from "fumadocs-ui/page";
import { createRelativeLink } from "fumadocs-ui/mdx";
import { notFound } from "next/navigation";
import { CombinedAIButton } from "@/components/page-actions";
import { DocsPageFooter } from "@/components/docs-page-footer";
import { source } from "@/lib/source";
import { getMDXComponents } from "@/mdx-components";

export default async function Page(props: { params: Promise<{ slug?: string[] }> }) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;
  const filePath = page.file.path;
  const isAutoGenerated = filePath.startsWith("spec/");
  const githubUrl = isAutoGenerated
    ? `https://github.com/dodopayments/dualmark/tree/main/spec`
    : `https://github.com/dodopayments/dualmark/blob/main/apps/docs/content/docs/${filePath}`;
  const rawUrl = `/raw${page.url}`;

  return (
    <DocsPage
      toc={page.data.toc}
      full={page.data.full}
      breadcrumb={{ includePage: true, includeSeparator: true }}
    >
      <DocsTitle className="flex flex-row items-start justify-between gap-4">
        <span>{page.data.title}</span>
        <div className="hidden shrink-0 md:block">
          <CombinedAIButton
            rawUrl={rawUrl}
            githubUrl={githubUrl}
            title={page.data.title}
          />
        </div>
      </DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <div className="mb-6 flex flex-row items-center gap-2 border-b border-[var(--color-border)] pb-6 md:hidden">
        <CombinedAIButton
          rawUrl={rawUrl}
          githubUrl={githubUrl}
          title={page.data.title}
        />
      </div>
      <DocsBody>
        <MDX components={getMDXComponents({ a: createRelativeLink(source, page) })} />
        <DocsPageFooter filePath={filePath} isAutoGenerated={isAutoGenerated} />
      </DocsBody>
    </DocsPage>
  );
}

export function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(props: { params: Promise<{ slug?: string[] }> }) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) return {};
  return {
    title: page.data.title,
    description: page.data.description,
  };
}
